version: '3.7'

services:
  #  gohu-web:
  #    build: .
  #    container_name: gohu-web
  #    restart: always
  #    ports:
  #      - "8083:8083"
  #    networks:
  #      - gohu_net
  oauth-api:
    build: app/service/oauth/api
    container_name: gohu-oauth-api
    restart: always
    ports:
      - "11110:11110"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net

  oauth-rpc-token-enhancer:
    build: app/service/oauth/rpc/token/enhancer
    container_name: gohu-oauth-rpc-token-enhancer
    restart: always
    ports:
      - "11111:11111"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net

  oauth-rpc-token-store:
    build: app/service/oauth/rpc/token/store
    container_name: gohu-oauth-rpc-token-store
    restart: always
    ports:
      - "11112:11112"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net

  user-api:
    build: app/service/user/api
    container_name: gohu-user-api
    restart: always
    ports:
      - "11120:11120"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net

  user-rpc-crud:
    build: app/service/user/rpc/crud
    container_name: gohu-user-rpc-curd
    restart: always
    ports:
      - "11121:11121"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net

  user-rpc-info:
    build: app/service/user/rpc/info
    container_name: gohu-user-rpc-info
    restart: always
    ports:
      - "11122:11122"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net

  user-rpc-vip:
    build: app/service/user/rpc/vip
    container_name: gohu-user-rpc-vip
    restart: always
    ports:
      - "11123:11123"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net


  question-api:
    build: app/service/question/api
    container_name: gohu-question-api
    restart: always
    ports:
      - "11130:11130"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net

  question-rpc-curd:
    build: app/service/question/rpc/crud
    container_name: gohu-question-crud-rpc
    restart: always
    ports:
      - "11132:11132"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net

  question-rpc-info:
    build: app/service/question/rpc/info
    container_name: gohu-question-info-rpc
    restart: always
    ports:
      - "11133:11133"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net


  comment-api:
    build: app/service/comment/api
    container_name: gohu-comment-api
    restart: always
    ports:
      - "11140:11140"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net

  comment-rpc-crud:
    build: app/service/comment/rpc/crud
    container_name: gohu-comment-rpc-crud
    restart: always
    ports:
      - "11142:11142"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net

  comment-rpc-info:
    build: app/service/comment/rpc/info
    container_name: gohu-comment-rpc-info
    restart: always
    ports:
      - "11143:11143"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net


  notification-api:
    build: app/service/notification/api
    container_name: gohu-notification-api
    restart: always
    ports:
      - "11150:11150"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net

  notification-rpc-crud:
    build: app/service/notification/rpc/crud
    container_name: gohu-notification-rpc-crud
    restart: always
    ports:
      - "11151:11151"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net

  notification-rpc-info:
    build: app/service/notification/rpc/info
    container_name: gohu-notification-rpc-info
    restart: always
    ports:
      - "11152:11152"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net


  mq-asynq-scheduler:
    build: app/service/mq/asynq/scheduler
    container_name: gohu-mq-asynq-scheduler
    restart: always
    ports:
      - "11161:11161"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net

  mq-asynq-processor:
    build: app/service/mq/asynq/processor
    container_name: gohu-mq-asynq-processor
    restart: always
    ports:
      - "11162:11162"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net

  mq-nsq-consumer:
    build: app/service/mq/nsq/consumer
    container_name: gohu-mq-nsq-consumer
    restart: always
    ports:
      - "11163:11163"
    environment:
      - TZ=Asia/Shanghai
      - APOLLO_APP_ID=${APOLLO_APP_ID}
      - APOLLO_CLUSTER_NAME=${APOLLO_CLUSTER_NAME}
      - APOLLO_IP=${APOLLO_IP}
      - APOLLO_SECRET=${APOLLO_SECRET}
    networks:
      - gohu_net


networks:
  gohu_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
